### ISSUE TITLE
Pbl statement review

### ISSUE THREAD

**Issue by slimpotatoes** [slimpotatoes/STEM_Moire_GPA#1]
Hi Dr. Smith,

Sorry I forgot to call the issue to review my problem statement before the deadline. Here is done now, if it's not too late. I'm personally not fully satisfied about what I wrote since it's too vague but I did not want to conflict between the what and the how. I will put more details and all the math when we are talking about the "how". If it's needed, I can edit the problem statement and add more details about the methodologies.

Regards,

Alex

**Comment by smiths** [comment]
Hello @slimpotatoes.  I approve your problem statement.  It is longer than it needs to be, with more background information than I expected, but that is fine.  You have a statement about the input and the expected output and that is the right thing to get you started.

I noticed a few LaTeX issues.  I'll push a version of your problem statement tex file with comments.
