### ISSUE TITLE
Test Plan (Non-Functional Test 9): Reasonable Execution Time

### ISSUE THREAD

**Issue by GenevaS** [slimpotatoes/STEM_Moire_GPA#15]
Similar to the "reasonable error" question: what would be considered a reasonable execution time? Can you set an upper bound on what you expect the software to ideally handle?

**Comment by slimpotatoes** [comment]
As suggested by @smiths on the same aspect, Test 9 has been modified to plot the execution time vs data size and show as a reference to compare with other software. This way one value for the execution doesn't need to be specified and still provide information of software performance.
