### ISSUE TITLE
SRS Document review

### ISSUE THREAD

**Issue by slimpotatoes** [slimpotatoes/STEM_Moire_GPA#2]
Hi @smiths,

The SRS document is ready to be reviewed. It is very likely that I will have to modify some sections in the future since the more I think about the software the more I see aspects to improve and to document. As a uneducated software engineer, I found sometimes difficult to follow the template and grasp the deeper sense of the various terminologies but I think that I manage to understand the main points. 

For your information, I took the freedom to remove the table format from Theoretical Models, Data Definitions and Instance Models sections because of the complexity to describe some of them. I needed some spaces to write down multiple sequences of equations and I found limited by the table format. I could have used the appendix to provide all the mathematical aspects but I figured out that the equations used in the different sections would look to come from no where. The complexity might also highlight that i did not manage to decompose the software into simple small pieces but after trying to simplify the problem I finished with a very high number of theoretical models and data definitions. Therefore, the document I propose is a kind of compromise trying to split the complexity in "simple" parts while keeping a "manageable" number of parameters.

I will be pleased to read your comments about the document.

Regards

Alexandre Pofelski

**Comment by smiths** [comment]
Thanks for the information Alex.  I look forward to looking over your SRS.  The eventual goal is to decompose the problem into small enough chunks that the information can be captured effectively in a knowledge base.  However, this may be more difficult for your problem.  It will be interesting to see the compromises you have come up with.
