### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by smiths** [slimpotatoes/STEM_Moire_GPA#20]
Add a .gitignore file with the content including the standard LaTeX file types.

**Comment by slimpotatoes** [comment]
Hi @smiths,

A .gitignore file is already present. Do I miss something ? :). Should I add other files in the .gitignore ?

![image](https://user-images.githubusercontent.com/22404010/32700670-35345a22-c796-11e7-843d-8d57627ff551.png)

**Comment by smiths** [comment]
Hi @slimpotatoes.  I believe the problem is that you do not have your .gitignore file under version control.  It does not appear on the web-interface for the repo, and it does not exist in my checkout version of your repo.

**Comment by slimpotatoes** [comment]
Hi @smiths,

I got it ... Didn't understood properly what the .gitignore file was doing. File added.

**Comment by smiths** [comment]
That sorted it out.  Thank you.
