### ISSUE TITLE
Generic Plot should be a separate module

### ISSUE THREAD

**Issue by renjiezhang** [slimpotatoes/STEM_Moire_GPA#23]
I think the plot is different with the generic controls such as buttons and windows. You may need more complex code to implement it.

**Comment by renjiezhang** [comment]
@smiths

**Comment by slimpotatoes** [comment]
I will join this comment your the other one discussing about the GUI modules discussion.  You are probably right and this will show up when writing the MIS. Overall the GUI subject is not an easy task and do not fit entirely the scope of the scientific computing subject. With the amount of work the other modules are requesting, I will put the GUI description in lower priority :). But for sure, I will have to do everything properly if I want to release a decent software.
