### ISSUE TITLE
In the hierarchy diagram, Stem moire GPA control Module needs to use Data structure 

### ISSUE THREAD

**Issue by renjiezhang** [slimpotatoes/STEM_Moire_GPA#24]
In the definition,Data structure provides GPA control module the format to store, read and manipulate all elements from an image. I think you need to link them.

**Comment by renjiezhang** [comment]
@smiths

**Comment by slimpotatoes** [comment]
Yes you're right and there are indeed linked. The three arrows on the bottom right are expressing that all modules from the hierarchy diagram use Data structure Module.
