### ISSUE TITLE
GPA control module needs to use Object Structure Module

### ISSUE THREAD

**Issue by renjiezhang** [slimpotatoes/STEM_Moire_GPA#25]
In the definition,Object Structure Module provides object format usable by module called by the control module.  I think you need to link them.

**Comment by renjiezhang** [comment]
@smiths

**Comment by slimpotatoes** [comment]
After some thinking, I decided to remove the Object Structure Module for two reasons:
- I got very confused on what to put in the MIS document about this module. 
- I think that the data structure is enough for STEM Moire GPA execution. I don't see what the object structure is bringing more in the design.

I'm not entirely fixed on what to do with this module but yes you're right control module should use the object structure so as the other modules. That is why I put three arrows on the top of the object structure module.
