### ISSUE TITLE
SRS: System Constraints

### ISSUE THREAD

**Issue by aschaap** [slimpotatoes/STEM_Moire_GPA#3]
The first mention of a detector occurs in the system constraints section. If I understand what follows afterwards, it detects the number of electrons crossing a sample at a certain location, but when first reading it I wasn't sure what was being referred to. Perhaps a clarification or a reference to figure 1 or the corresponding explanation would help to avoid such confusion?

**Comment by slimpotatoes** [comment]
Added the definition of detector in the terminology definition section and a reference to fig 1 for clarity.
