### ISSUE TITLE
SRS: Terminology and Definitions

### ISSUE THREAD

**Issue by aschaap** [slimpotatoes/STEM_Moire_GPA#4]
This may reflect my lack of background knowledge, so please disregard this issue if this is obvious to other readers, but what is the O in the definition of the 2D Cartesian coordinate system? (There seems to be no entry in the table of symbols.)

**Comment by slimpotatoes** [comment]
O is the origin of the 2D cartesian coordinate system and was not defined at all :). Sorry for that. Added O in the symbol table and clarified the definition as well.
